[build]
  publish = "."
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/"
  to = "/ux-ui-landing.html"
  status = 200

[[redirects]]
  from = "/ux-ui"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/figma"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/design"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/ux-ui-free-lesson"
  to = "/ux-ui-free-lesson.html"
  status = 200

[[redirects]]
  from = "/figma-lesson"
  to = "/ux-ui-free-lesson.html"
  status = 200

[[redirects]]
  from = "/landing"
  to = "/landing.html"
  status = 200

[[redirects]]
  from = "/code-course"
  to = "/landing.html"
  status = 200

[[redirects]]
  from = "/free-lesson"
  to = "/free-lesson.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/preorders-dashboard.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 